### ISSUE TITLE
AlonsoLevels fails to start when gringotts-2.12.2.jar is installed at the same time.

### ISSUE THREAD

**Issue by dfeneck** [AlonsoAliaga/AlonsoLevels#6]
**Describe the bug**
AlonsoLevels crashes on startup, but only when I have gringotts-2.12.2.jar enabled.
The error that I get is a null ref to 'this.plugin'.

Interestingly AlonsoLeagues didn't crash and worked fine with gringotts enabled.

**Important (please complete the following information):**
 - Java version: 17
 - Plugin version: 2.2.3-BETA
![AlonsoLevels error](https://user-images.githubusercontent.com/78724526/148425450-c59b8c3f-ac52-4d59-a3d0-ddc68dc30a73.png)

 - Server version 1.18 spigot

**Comment by AlonsoAliaga** [comment]
Sadly some plugins completely break order of plugin loading. In this case AlonsoLeaderboards should be loaded before AlonsoLevels, however (as stated above) some plugins (somehow) breaks loading order making it enable after AlonsoLevels. That can't be "fixed" (at lesst for now, it's actually not my plugin issue). I dont know why that happens as AlonsoLevels depends on AlonsoLeaderboards which should make it enable after AlonsoLeaderboards. But as order is broken by some plugins, it simply doesnt load.
You can:
1) Disable leaderboards in AlonsoLevels config.yml
2) Remove AlonsoLeaderboards
But as stated, this is nlt a plugin issue, some plugins simply break loading order.
I try to "implement a fix" (even when it's not caused by my plugin) but it **wont** be available soon as AlonsoLeaderboards is not receiving updates for now. (No time enough, college; several internal changes in a build i made and wasnt finished)
I think i was clear, feel free to join my discord server for more questions

**Comment by dfeneck** [comment]
Hey thanks for your speedy reply!
It was 6am in the morning and I hadn't slept yet so I hit the sack for some much needed sleep.

Once I woke up, your comment got me thinking, if its simply a plugin load order issue, you simply need to re-config your plugin.yml files in your plugins, which is something I can do myself by opening and editing the jars I have :smile:

So sure enough, I got it to work with this method.

**I added into Leaderboards plugin.yml:**
`loadbefore: [AlonsoLevels, AlonsoLeagues]`

**I added into Leagues and Levels plugin.yml's:**
```
depend:
- AlonsoLeaderboards
```

And now everything is running with gringotts running as well, I just logged in and confirmed all plugins are working!
Hopefully now you can fix this issue up for anyone else having this trouble too :)

Again, thanks for your speedy reply. I really like these plugins and hope to use them for our server going forward, I'll even pay for pro most likely.

Cheers,
Fen from The Motherland

**Comment by AlonsoAliaga** [comment]
Glad to hear it's working for you. Sadly on my side it's not that easy.
1) AlonsoLeaderboards was not updated in a long time, I have a lot of work before a new update is releas (nontime for now)
2) I can't simply add "depend" in Levels and Leagues plugins, because AlonsoLeaderboards is not a depend, it's a soft depend (I cannot tell people its required, Inmade it to be optional)

I have other ways to "fix" this kind of issues, but I need to wait until I'm able to update AlonsoLeaderboards again.

Have a good day!

**Comment by AlonsoAliaga** [comment]
Just wondering, you tested latest version with leaderboards enabled?

**Comment by dfeneck** [comment]
Hey I have tested the latest versions. Working well it seems!
