### ISSUE TITLE
If you use 2.2.4-BETA and open a GUI, the Experience Bar is gone until you relog/reload the plugin.

### ISSUE THREAD

**Issue by Nigolaudo** [AlonsoAliaga/AlonsoLevels#7]
If you use 2.2.4-BETA and open a GUI, the Experience Bar is gone until you relog/reload the plugin.

**Comment by AlonsoAliaga** [comment]
> If you use 2.2.4-BETA and open a GUI, the Experience Bar is gone until you relog/reload the plugin.

Code for "Exp bar" hasn't been updated in a long time, so that should happen in all previous versions (except for PRO version which have a different system). Plugin works fine, there must be another plugin which update exp bar on inventory open.
Constant exp bar update is a PRO feature, not a feature of Free version. That only updates on exp gain/lose/update or reconnect (on the other hand, PRO version updates it every X seconds/minutes to "fix" the problem)
However, the thing is that we work with PACKETS, basically any change of exp (and some other stuff) updates player profile which updates also exp bar player sees, hence why code was modified in PRO version to update it regularely. (Not free version)
